### PR TITLE
Add credits and logos in README

### PR DESCRIPTION
**Pull request by vogelino**
@ff6347 @dnsos do you think we should also add the contributors to this repo or only to the individual repos?

**See the README here:**
https://github.com/technologiestiftung/stadtpuls/tree/credits-in-readme#readme

### CODE REVIEW

**Review by Esshahn — CHANGES_REQUESTED** [review]
Please replace ## Kredite with ## Credits 
like in the english version

**Comment by dnsos** [comment]
> @ff6347 @dnsos do you think we should also add the contributors to this repo or only to the individual repos?

I would say to add them here for docs work.

**Comment by ff6347** [comment]
> >   @ff6347 @dnsos do you think we should also add the contributors to this repo or only to the individual repos?
> I would say to add them here for docs work.

I would vote for adding them to the repo where to contribution happens. Since adding them also here is a maintenance burden.

**Comment by vogelino** [comment]
> I would vote for adding them to the repo where to contribution happens.

I think I agree with that. I'm not sure maintaining the contributors here for docs is worth it. @dnsos do you agree?

**Review by ff6347 — APPROVED** [review]

**Comment by dnsos** [comment]
@vogelino I was about to suggest you break the tie :D No worries, I'm fine with that.

**Review by Esshahn — CHANGES_REQUESTED** [review]
I'd suggest to have a repo for the logos so we are not depending on the wordpress site structure.
If we put the logos (in fact we could store all kinds of logos there) in a separate repo, we only need to update that repo and all pages will get updated automatically.
What do you think?

**Comment by vogelino** [comment]
> I'd suggest to have a repo for the logos so we are not depending on the wordpress site structure. If we put the logos (in fact we could store all kinds of logos there) in a separate repo, we only need to update that repo and all pages will get updated automatically. What do you think?

I think it is a good idea for GitHub! I'm not sure about the websites, however, as we might face cross-origin problems. This server could be adde to the CSP but I'm not sure... Also, if the logo dimensions change, we might still need to go through each project and change the CSS. But not necessarily. Kind of undecided, as you might notice 😅

**Comment by Esshahn** [comment]
I'm not sure I understood you right, I'll try to be more precise :)
I would not use logos from our wordpress site:
`https://citylab-berlin.org/wp-content/uploads/2021/05/citylab-logo.svg`
but instead have a URL that points to one of our repos that we could create for this use case, like
`https://github.com/technologiestiftung/media-files/citylab-logo.svg`

**Comment by ff6347** [comment]
> I'm not sure I understood you right, I'll try to be more precise :)
> 
> I would not use logos from our wordpress site:
> 
> `https://citylab-berlin.org/wp-content/uploads/2021/05/citylab-logo.svg`
> 
> but instead have a URL that points to one of our repos that we could create for this use case, like
> 
> `https://github.com/technologiestiftung/media-files/citylab-logo.svg`
> 
> 
> 
> 

+1 on this. 

Needs to be the raw.githubusercontent url though

**Comment by ff6347** [comment]
OR we put the logos for this purpose into https://github.com/technologiestiftung/template-default and dogfood it.

**Comment by vogelino** [comment]
> I'm not sure I understood you right

I thought you weren't limiting this idea to github repos only, but that you wanted to deploy the logos somewhere and have all our websites point to that. If you only talk about github, then I agree! Forget what I said!

> OR we put the logos for this purpose into https://github.com/technologiestiftung/template-default and dogfood it.

I think this is a great idea!

**Comment by ff6347** [comment]
Let's only do github for starters and only do it for the repos derived from this template.

**Comment by vogelino** [comment]
On second thought, we will need to add the logos of ODIS, SenWEB, etc. because the supporter aren't always the same. Do we want to have all those logos there? Think about the fact, that those will be duplicated each time the template is used.

**Pull request merged**
